const config = {
    parent:document.body,
    width:"384px",
    fontSize:"16px",
    buttons: [
        {
            label:"Gestionnaires",
            buttons:[
                {
                    label:"Ingrédients",
                },
                {
                    label:"Commentaires",
                },
                {
                    label:"Allergènes",
                },
                {
                    label:"Ressources",
                },
                {
                    label:"Imprimantes",
                },
                {
                    label:"Tableur"
                }
            ]
        },
        {
            label:"Paramètres",
            buttons:[
                {
                    label:"Mise en page"
                },
                {
                    label:"Langue",
                    buttons:[
                        {
                            label:"Français"
                        },
                        {
                            label:"Anglais"
                        },
                        {
                            label:"Espagnol"
                        },
                        {
                            label:"Italien"
                        },
                        {
                            label:"Portuguais"
                        },
                        {
                            label:"Allemand"
                        },
                        {
                            label:"Russe"
                        },
                        {
                            label:"Arabe"
                        }
                    ]
                },
                {
                    label:"Borne"
                },
                {
                    label:"Type de Vente"
                },
                {
                    label:"Tout Voir"
                },
                {
                    label:"Aides Visuelle"
                }
            ]
        },
        {
            label:"Outils",
            buttons:[
                {
                    label:"Copier"
                },
                {
                    label:"Coller"
                },
                {
                    label:"Supprimer"
                },
                {
                    label:"Corbeille"
                }
            ]
        },
        {
            label:"Ajouter",
            buttons:[
                {
                    label:"Catégorie"
                },
                {
                    label:"Produit"
                },
                {

                }
            ]
        }
    ],
    onSelect:function(index, value) { alert(`Bouton ${value}(${index}) sélectionné`) }
};
const radial = new RadialMenu(config);